name: StandardJS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

defaults:
  run:
    shell: bash

permissions:
  contents: read

jobs:
  standardjs:
    name: StandardJs
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: StandardJs
      uses: docker://jopereyral/standardjs-action
      with:
        args: --fix